"""Export a trained policy network's weights to a C header.

The C inference code (cnn/policy_net.c) bakes these weights in and runs the
forward pass in pure C -- microsecond-scale, no Python or PyTorch at runtime.
Works for any network shape (reads the layers from the checkpoint).

    .venv\\Scripts\\python scripts/export_weights.py --champion runs_final/best.pt
"""

import argparse
import pathlib
import sys

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent.parent))

import torch
import torch.nn as nn

from mancala_rl.network import load_net


def main():
    p = argparse.ArgumentParser()
    p.add_argument("--champion", default="runs_final/best.pt")
    p.add_argument("--out", default="cnn/policy_weights.h")
    args = p.parse_args()

    net = load_net(args.champion)            # shape read from the checkpoint

    # The PolicyBot forward path: the hidden Linear layers (each followed by a
    # ReLU) then the policy head (no activation). The value head is unused.
    linears = [m for m in net.body if isinstance(m, nn.Linear)] + [net.policy_head]

    def fmt(values):
        return ",".join(f"{float(v):.9g}f" for v in values)

    lines = ["// generated by scripts/export_weights.py -- do not edit by hand"]
    lines.append(f"#define IN_DIM {linears[0].in_features}")
    lines.append(f"#define OUT_DIM {linears[-1].out_features}")
    lines.append(f"#define NUM_LAYERS {len(linears)}")
    for i, lin in enumerate(linears):
        lines.append(f"static const float W{i}[] = {{{fmt(lin.weight.detach().flatten().tolist())}}};")
        lines.append(f"static const float b{i}[] = {{{fmt(lin.bias.detach().tolist())}}};")
    lines.append("typedef struct { int in, out; const float *W; const float *b; } Layer;")
    table = ", ".join(f"{{{lin.in_features},{lin.out_features},W{i},b{i}}}"
                      for i, lin in enumerate(linears))
    lines.append(f"static const Layer LAYERS[NUM_LAYERS] = {{{table}}};")

    out = pathlib.Path(args.out)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text("\n".join(lines) + "\n")
    params = sum(lin.weight.numel() + lin.bias.numel() for lin in linears)
    print(f"wrote {out}  ({len(linears)} layers, {params:,} parameters)")


if __name__ == "__main__":
    main()
